esphome:
  name: esphome-web-852174
  friendly_name: ESPHome Web 852174
  compile_process_limit: 1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "J2lYElo1QpuPAMkPFmTtq3Cmc4llzurNlXbhjc2G/Io="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-852174"
    password: "Ep9AtoJOX7f1"

captive_portal:
    
esp32:
  board: m5stack-atom

web_server:
  port: 80

uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://joloman2/esphome_samsung_heatpump@main
    components: [samsung_hp]

samsung_hp:
  devices:
    - address: "20.00.00" # for non NASA it sould be like "c4"
      # Each property below are optional - choose what you want to use.

      # You could use the ESPHome/Homeassist climate control
      #climate:
        #name: "My Room"

      # And/or use seperate controls/sensors
      #room_temperature:
        #name: Test1_temp
      #target_temperature:
        #name: Test1_target
      power:
        name: DHW Power
      mode:
        name: DHW Mode

      # Only supported on NASA devices
      #room_humidity:
        #name: Test1_humidity